
name: Build Grim Scaffold

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Verify Meteor jar present
        run: |
          if [ ! -f "libs/meteor-client-1.21.5-54.jar" ]; then
            echo "::error::Missing libs/meteor-client-1.21.5-54.jar. Commit your Meteor jar into libs/ first."
            exit 1
          fi

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew --no-daemon --refresh-dependencies clean build

      - name: Upload mod artifact
        uses: actions/upload-artifact@v4
        with:
          name: grimscaffold-jar
          path: build/libs/*.jar
